Repository Lane-G-Smith/AI-Personalities-React-App, pull requests merged in 2023-09, with the labels that each got.

#15 Add types and formatter
  .eslintrc
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  public/output.css
  src/App.jsx
  src/App.tsx
  src/input.css
  src/main.jsx
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tailwind.config.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.js
  vite.config.ts
Labels: enhancement

#11 Added broken dark mode toggle
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/components/DarkMode/DarkBtn.tsx
  src/components/DarkMode/DarkMode.ts
  src/input.css
  src/main.tsx
  src/output.css
  tsconfig.json
Labels: enhancement, help wanted, good first issue

#21 Merge Express API w/ ESM, TS, ESLint, package upgrades
  .eslintrc
  .gitignore
  .prettierrc
  LICENSE
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/routes/chatBots.js
  backend/routes/chatBots.ts
  backend/server.js
  backend/server.ts
  backend/tsconfig.json
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DarkMode/DarkMode.ts
  package-lock.json
  package.json
Labels: enhancement, good first issue
